# Generated by Django 4.2.7 on 2023-12-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '3. Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '2. Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name_plural': '1. Instructor'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '4. Student'},
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='address',
        ),
        migrations.AddField(
            model_name='instructor',
            name='skills',
            field=models.CharField(default='SomeDefaultValue', max_length=100),
        ),
    ]
